/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author petroski
 */
public class ViewCliente extends javax.swing.JPanel {

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout());
        jPanel2.add(jSeparator1);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);

        jTextField3.setText("jTextField3");
        jPanel3.add(jTextField3);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jTextField4.setText("jTextField4");
        jPanel3.add(jTextField4);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        jTextField1.setText("jTextField1");
        jPanel4.add(jTextField1);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
